#!/usr/bin/env bash
# Build the dashboard's live data and publish it to the `dashboard-data` branch.
#
#   scripts/publish_dashboard.sh             # build, commit, force-push
#   scripts/publish_dashboard.sh --dry-run   # build and commit locally; no push
#
# The branch holds exactly one commit (no parent) with status.json,
# seastate/*.json and manifest.json, so hourly updates do not grow history.
# The commit is made with git plumbing against a temporary index: the working
# tree, the real index, and the checked-out branch are never touched, so it is
# safe to run while you work in this checkout. The dashboard reads the branch
# through raw.githubusercontent.com (see docs/operations/dashboard.md).
#
# Environment: WAVE_ANALYSIS_DASHBOARD_REMOTE (default: origin),
#              WAVE_ANALYSIS_DASHBOARD_BRANCH (default: dashboard-data).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REMOTE="${WAVE_ANALYSIS_DASHBOARD_REMOTE:-origin}"
BRANCH="${WAVE_ANALYSIS_DASHBOARD_BRANCH:-dashboard-data}"
DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
OUT="$WORK/live"

"$REPO/.venv/bin/wave-analysis" dashboard live --out "$OUT"

export GIT_INDEX_FILE="$WORK/index"
git -C "$REPO" read-tree --empty
(
    cd "$OUT"
    find . -type f -name '*.json' -print0 | sort -z | while IFS= read -r -d '' f; do
        path="${f#./}"
        blob="$(git -C "$REPO" hash-object -w -- "$f")"
        git -C "$REPO" update-index --add --cacheinfo "100644,$blob,$path"
    done
)
tree="$(git -C "$REPO" write-tree)"
stamp="$(date -u +%FT%TZ)"
commit="$(git -C "$REPO" commit-tree "$tree" -m "Dashboard live data $stamp" \
    -m "Generated by scripts/publish_dashboard.sh; replaces the previous snapshot.")"
unset GIT_INDEX_FILE

if (( DRY_RUN )); then
    echo "$stamp dry run: built $commit (tree $tree); not pushed"
    exit 0
fi
git -C "$REPO" push --force --quiet "$REMOTE" "$commit:refs/heads/$BRANCH"
echo "$stamp published $commit to $REMOTE/$BRANCH"
